### ISSUE TITLE
[Bug] Crash on android 13

### ISSUE THREAD

**Issue by dgudim** [qwq233/Nullgram#177]
### Steps to reproduce

Open the app

### Expected behaviour

App opens

### Actual behaviour

App crashes

### Smartphone Information

Os: android 13
One-ui: 5.1

### Nullgram Version

v9.6.7-ee9c46b 

### Version requirement

- [X] I am using latest debug CI version of Nullgram and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

FATAL EXCEPTION: main
Process: top.qwq2333.nullgram, PID: 10717
java.lang.UnsatisfiedLinkError: No implementation found for void org.telegram.tgnet.ConnectionsManager.native_setJava(boolean) (tried Java_org_telegram_tgnet_ConnectionsManager_native_1setJava and Java_org_telegram_tgnet_ConnectionsManager_native_1setJava__Z) - is the library loaded, e.g. System.loadLibrary?
	at org.telegram.tgnet.ConnectionsManager.native_setJava(Native Method)
	at org.telegram.messenger.ApplicationLoader.onCreate(ApplicationLoader.java:217)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7619)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by LucentW** [comment]
> v9.6.7-ee9c46b

I'm pretty sure it's not the latest debug CI version considering the actual latest build from master is `v10.2.6-preview-cae57e7` and the latest **release** version is `v10.2.3-05c0800`, which both run just fine on Android 13 and 14.

**Comment by qwq233** [comment]
It's a outdated version that I don't provide support anymore.
However, from the log you sent, it seems like this an issue with signature verify which means you're probably using a modified version of Nullgram.

**Comment by dgudim** [comment]
Where can I download the latest build?

**Comment by LucentW** [comment]
> Where can I download the latest build?

Releases from CI/CD get uploaded on https://t.me/NullgramAPKs, master builds on https://t.me/NullgramCI

**Comment by qwq233** [comment]
> > Where can I download the latest build?
> 
> Releases from CI/CD get uploaded on https://t.me/NullgramAPKs, master builds on https://t.me/NullgramCI

You can also get it from GitHub action or play store
